/* 由 gen_mini_espn.js 于 2026-09-12T21:27:54.620Z 从 tools/_live0912.js 生成, 勿手改 */
module.exports = {
  LEAGUES: {
    "周六003": "jpn.1",
    "周六004": "jpn.1",
    "周六005": "esp.1",
    "周六006": "ita.1",
    "周六007": "ger.1",
    "周六008": "ger.1",
    "周六009": "ger.1",
    "周六010": "ger.1",
    "周六011": "ger.1",
    "周六012": "eng.1",
    "周六013": "eng.1",
    "周六014": "eng.1",
    "周六015": "eng.1",
    "周六016": "eng.1",
    "周六017": "esp.1",
    "周六018": "fra.1",
    "周六019": "ksa.1",
    "周六020": "ita.1",
    "周六021": "nor.1",
    "周六022": "eng.1",
    "周六023": "ger.1",
    "周六024": "esp.1",
    "周六025": "por.1",
    "周六026": "ned.1",
    "周六027": "ita.1",
    "周六028": "fra.1",
    "周六029": "eng.1"
  },
  TEAM: {
    "广岛三箭": "Hiroshima",
    "大阪樱花": "Cerezo",
    "大阪钢巴": "Gamba",
    "东京FC": "FC Tokyo",
    "桑坦德": "Racing Santander",
    "阿拉维斯": "Alavés",
    "热那亚": "Genoa",
    "弗洛西诺": "Frosinone",
    "弗赖堡": "Freiburg",
    "门兴": "Mönchengladbach",
    "美因茨": "Mainz",
    "法兰克福": "Eintracht Frankfurt",
    "多特蒙德": "Dortmund",
    "帕德博恩": "Paderborn",
    "奥格斯堡": "Augsburg",
    "勒沃库森": "Leverkusen",
    "霍芬海姆": "Hoffenheim",
    "斯图加特": "Stuttgart",
    "切尔西": "Chelsea",
    "赫尔城": "Hull",
    "伯恩茅斯": "Bournemouth",
    "布伦特": "Brentford",
    "维拉": "Aston Villa",
    "诺丁汉": "Nottingham",
    "水晶宫": "Crystal Palace",
    "伊普斯": "Ipswich",
    "利物浦": "Liverpool",
    "富勒姆": "Fulham",
    "奥萨苏纳": "Osasuna",
    "西班牙人": "Espanyol",
    "斯特拉斯": "Strasbourg",
    "摩纳哥": "Monaco",
    "布赖合作": "Al Taawoun",
    "利雅新月": "Al Hilal",
    "拉齐奥": "Lazio",
    "AC米兰": "Milan",
    "罗森博格": "Rosenborg",
    "特罗姆瑟": "Tromso",
    "热刺": "Tottenham",
    "埃弗顿": "Everton",
    "科隆": "Cologne",
    "不来梅": "Werder",
    "毕尔巴鄂": "Athletic",
    "埃尔切": "Elche",
    "卡萨皮亚": "Casa Pia",
    "波尔图": "Porto",
    "福图纳": "Fortuna Sittard",
    "阿贾克斯": "Ajax",
    "亚特兰大": "Atalanta",
    "卡利亚里": "Cagliari",
    "巴黎FC": "Paris FC",
    "里昂": "Lyon",
    "桑德兰": "Sunderland",
    "阿森纳": "Arsenal"
  },
};
