/* 由 gen_mini_espn.js 于 2026-10-09T11:47:02.083Z 从 tools/_live1009.js 生成, 勿手改 */
module.exports = {
  LEAGUES: {
    "周六001": "jpn.1",
    "周六002": null,
    "周六003": null,
    "周六004": "jpn.1",
    "周六005": "eng.1",
    "周六006": "esp.1",
    "周六007": "ita.1",
    "周六008": "ger.1",
    "周六010": "ger.1",
    "周六011": "ger.1",
    "周六012": "ger.1",
    "周六013": "eng.1",
    "周六014": "eng.1",
    "周六015": "eng.1",
    "周六016": "esp.1",
    "周六017": "fra.1",
    "周六020": "eng.1",
    "周六021": "ger.1",
    "周六023": "ned.1",
    "周六024": "por.1",
    "周六026": "ned.1",
    "周六027": "ita.1",
    "周六028": "fra.1",
    "周六029": "esp.1"
  },
  TEAM: {
    "大阪樱花": "Cerezo",
    "横滨水手": "Marinos",
    "首尔FC": "Seoul",
    "济州SK": "Jeju",
    "金泉尚武": "Gimcheon",
    "安养FC": "Anyang",
    "京都": "Kyoto",
    "町田泽维": "Machida",
    "阿森纳": "Arsenal",
    "利兹联": "Leeds",
    "巴列卡诺": "Vallecano",
    "毕尔巴鄂": "Athletic",
    "热那亚": "Genoa",
    "佛罗伦萨": "Fiorentina",
    "柏林联合": "Union Berlin",
    "埃沃斯堡": "Elversberg",
    "美因茨": "Mainz",
    "勒沃库森": "Leverkusen",
    "帕德博恩": "Paderborn",
    "斯图加特": "Stuttgart",
    "霍芬海姆": "Hoffenheim",
    "汉堡": "Hamburg",
    "伊普斯": "Ipswich",
    "富勒姆": "Fulham",
    "切尔西": "Chelsea",
    "伯恩茅斯": "Bournemouth",
    "维拉": "Aston Villa",
    "布伦特": "Brentford",
    "阿拉维斯": "Alav",
    "马竞": "Atlético Madrid",
    "里尔": "Lille",
    "勒阿弗尔": "Havre",
    "曼联": "Manchester United",
    "热刺": "Tottenham",
    "莱红牛": "Leipzig",
    "法兰克福": "Frankfurt",
    "费耶诺德": "Feyenoord",
    "阿尔克马": "Alkmaar",
    "马里迪莫": "aritimo",
    "波尔图": "Porto",
    "福图纳": "Fortuna",
    "特温特": "Twente",
    "那不勒斯": "Napoli",
    "弗洛西诺": "Frosinone",
    "摩纳哥": "Monaco",
    "图卢兹": "Toulouse",
    "皇马": "Real Madrid",
    "比利亚雷": "Villarreal"
  },
};
