/* 由 gen_mini_espn.js 于 2026-09-15T09:02:59.595Z 从 tools/_live0915.js 生成, 勿手改 */
module.exports = {
  LEAGUES: {
    "周二001": "afc.champions",
    "周二002": "afc.champions",
    "周二004": "afc.champions",
    "周二005": "afc.champions",
    "周二006": "afc.champions",
    "周二007": "esp.1",
    "周二008": "esp.1",
    "周二013": "esp.1",
    "周二009": "ned.1",
    "周二010": "eng.2",
    "周二011": "eng.league_cup",
    "周二012": "eng.league_cup",
    "周二014": "conmebol.libertadores"
  },
  TEAM: {
    "叻武里": "Ratchaburi",
    "上海海港": "Shanghai Port",
    "大田市民": "Daejeon",
    "京都": "Kyoto",
    "柔佛": "Johor",
    "布里兰": "Buriram",
    "北京国安": "Beijing Guoan",
    "浦项制铁": "Pohang",
    "阿布艾因": "Al Ain",
    "利雅胜利": "Al Nassr",
    "巴列卡诺": "Rayo Vallecano",
    "西班牙人": "Espanyol",
    "阿拉维斯": "Alavés",
    "巴伦西亚": "Valencia",
    "阿贾克斯": "Ajax",
    "威廉二世": "Willem II",
    "米堡": "Middlesbrough",
    "米尔沃尔": "Millwall",
    "利物浦": "Liverpool",
    "热刺": "Tottenham",
    "伊普斯": "Ipswich",
    "阿森纳": "Arsenal",
    "埃尔切": "Elche",
    "皇马": "Real Madrid",
    "普拉滕斯": "Platense",
    "弗鲁米嫩": "Fluminense"
  },
};
